### PR TITLE
Added ConfigProvider making Config more extendable

### PR DESCRIPTION
**Pull request by psrok1**
Hi! 

First of all, I really appreciate all the work you've done with the typed-config library. 

I'm trying to find a good design pattern for configuration management in Python apps. In application we develop, we need to deal with different environments (perfect use-case for various `ConfigSource`) and because configuration constantly grows along with development of new features, we need some schemas/typings. It seems that your library fulfills almost all of my needs :)

The application we develop comes with a simple plugin system. Plugins need to be configured as well, so there must be a way to declare additional sections used by a plugin along with main configuration.

If I correctly understand the code: `Config` objects are bound together by common `_cache` and `_sources` objects. In this PR I've moved them to the separate object called `ConfigProvider`, shared across the instances. The provider makes the interface more flexible and it can be passed as an `__init__` argument and is exposed by `Config` instances.

Exposed `ConfigProvider` allows us to inherit from `Config` classes/objects, so it can be used by plugins to provide the extended view of the main configuration.

e.g. [`app/config.py`](https://github.com/psrok1/typed-config-pluggable-example/blob/master/app/config.py):
```python
from typedconfig import Config, key, group_key, section
from typedconfig.source import IniFileConfigSource, EnvironmentConfigSource


@section('database')
class DatabaseConfig(Config):
    """
    Database configuration
    """
    host = key(cast=str)
    port = key(cast=int)
    timeout = key(cast=float)


class ApplicationConfig(Config):
    """
    Main configuration object
    """
    database = group_key(DatabaseConfig)


config = ApplicationConfig(sources=[
    EnvironmentConfigSource(),
    IniFileConfigSource("config.ini")
])
```

can be extended by [`plugin/friendly_plugin.py`](https://github.com/psrok1/typed-config-pluggable-example/blob/master/plugins/friendly_plugin.py) by binding `ConfigProvider` exposed by the main configuration object with a plugin's own class:

```python
from typedconfig import Config, section, group_key, key

from app.config import ApplicationConfig, config


@section("friendly_plugin")
class WhatToSayConfig(Config):
    """
    Additional section with plugin-specific configuration
    """
    what_to_say = key(cast=str)


class FriendlyPluginConfig(ApplicationConfig):
    """
    Main configuration object extended by plugin-specific sections
    """
    friendly_plugin = group_key(WhatToSayConfig)


# Use common provider with app configuration
config = FriendlyPluginConfig(provider=config.provider)


def execute():
    # Usage of plugin-specific values
    print(f"Friendly Plugin says {config.friendly_plugin.what_to_say}")
    # Usage of application-wide values
    print(f"Let's pretend that we're connecting to {config.database.host}:{config.database.port}...")
```

Usage example can be also find here: https://github.com/psrok1/typed-config-pluggable-example

What do you think about it? If you want me to provide some feature-specific tests or an additional section in README, just let me know!

I propose that as a more clean alternative to "dynamic section injection" approach suggested in #1.

### CODE REVIEW

**Comment by bwindsor** [comment]
Thanks for the PR! As I gradually understood what you had changed, I started to really like it. This is a really nice refactor, it makes the code simpler and more extensible, and removes all but one of the `@_propagate_to_children` decorators which I was having to use before.

I've added some more tests, resolved merge conflicts, and some more minor changes.

Please could you add a section in the readme with documentation/examples for how to use `ConfigProvider`?

**Comment by bwindsor** [comment]
I was just looking at how you're using typed-config in mwdb, and saw this code:
```
def reload_config():
    app_config.provider._config_sources = _config_sources()
    app_config.provider.clear_cache()
```
I'm just interested, why is it necessary to replace the config sources, why is it not sufficient just to clear the cache?

**Comment by psrok1** [comment]
Hi! Sure, I will add that section to README.md :+1: 

I fully understand that delay and sorry not to ping your earlier, GH notifications are complete mess and it's quite often to miss some PRs/issues. Just saw that you were not so active in this repository so I decided not to bother you and wait patiently a bit longer until you come back :smile: 

Regarding to `_config_sources` replace, file contents are read by `IniFileConfigSource.__init__` so if you want to read the referenced file once again, you need to recreate the objects. And that was my case: in the "first configuration" tool, I create the configuration file from template based on values provided by user, so in the next configuration step - I need to reinitialize the sources.

**Comment by psrok1** [comment]
Alright, I've added some documentation. Is it OK? :wink:

**Comment by bwindsor** [comment]
That looks good, thank you! Will merge now.

**Comment by bwindsor** [comment]
This is available in `0.2.0`

I've also added a `replace_source` and `set_sources` method, avaliable in `0.2.1` which should mean your reload function shouldn't need to access the internal `_config_sources` member any more, like this:
```
def reload_config():
    app_config.provider.set_sources(_config_sources())
    app_config.provider.clear_cache()
```
Or you could use the `replace_source` method to just replace the one souce which reads the file.
Documentation for that is in the README [here](https://github.com/bwindsor/typed-config#modifying-or-refreshing-configuration-after-it-has-been-loaded)

**Comment by psrok1** [comment]
Thanks! I've checked the changes and will move to `0.2.1` as soon as it will be available on PyPi.

**Comment by bwindsor** [comment]
No problem! `0.2.1` is now there.

**Pull request merged**
